language: node_js
node_js:
  - '0.10'
services:
  - mongodb
install:
  - npm install
  - webdriver-manager update --standalone
before_script:
  - 'npm install -g grunt-cli mocha'
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - nohup bash -c "webdriver-manager start 2>&1 &"
  - cp config.json.example config.json
